web-app/Pages/Account/Login.cshtml.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using DAL.EF;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace web_app.Pages.Account
{
    [AllowAnonymous]
    public class LoginModel : PageModel
    {
        private readonly UserManager<SportsHubUser> _userManager;
        private readonly SignInManager<SportsHubUser> _signInManager;
        private readonly ILogger<LoginModel> _logger;

        public LoginModel(SignInManager<SportsHubUser> signInManager,
            ILogger<LoginModel> logger,
            UserManager<SportsHubUser> userManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _logger = logger;
        }

        [BindProperty]
        public InputModel Input { get; set; }

        public IList<AuthenticationScheme> ExternalLogins { get; set; }

        public string ReturnUrl { get; set; }

        [TempData]
        public string ErrorMessage { get; set; }

        public class InputModel
        {
            [Required]
            [EmailAddress(ErrorMessage = "Please enter valid email")]
            public string Email { get; set; }

            [Required]
            [DataType(DataType.Password)]
            public string Password { get; set; }

            [Display(Name = "Remember me?")]
            public bool RememberMe { get; set; }
        }

        private void SetViewData()
        {
            ViewData["Title"] = "Log In";
            ViewData["OtherOptionSpan"] = "Don't have an account?";
            ViewData["OtherOptionLink"] = "/Account/Register";
            ViewData["OtherOption"] = "Get Started";
        }

        public async Task OnGetAsync(string returnUrl = null)
        {
            if (!string.IsNullOrEmpty(ErrorMessage))
            {
                ModelState.AddModelError(string.Empty, ErrorMessage);
            }

            returnUrl ??= Url.Content("~/");

            await HttpContext.SignOutAsync(IdentityConstants.ExternalScheme);

            ReturnUrl = returnUrl;
            SetViewData();
        }

        public async Task<IActionResult> OnPostAsync(string returnUrl = null)
        {
            returnUrl ??= Url.Content("~/");


            if (ModelState.IsValid)
            {
                var result = await _signInManager.PasswordSignInAsync(Input.Email, Input.Password, Input.RememberMe, lockoutOnFailure: false);
                if (result.Succeeded)
                {
                    _logger.LogInformation("User logged in.");
                    return LocalRedirect(returnUrl);
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Invalid login attempt.");
                    SetViewData();
                    return Page();
                }
            }

            SetViewData();
            return Page();
        }
    }
}

web-app/Pages/Account/Logout.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DAL.EF;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace web_app.Pages.Account
{
    [Authorize(Roles = "Admin, User")]
    public class LogoutModel : PageModel
    {
        private readonly SignInManager<SportsHubUser> _signInManager;
        private readonly ILogger<LogoutModel> _logger;

        public LogoutModel(SignInManager<SportsHubUser> signInManager, ILogger<LogoutModel> logger)
        {
            _signInManager = signInManager;
            _logger = logger;
        }

        public async Task<IActionResult> OnGet(string returnUrl = "Index")
        {
            await _signInManager.SignOutAsync();
            _logger.LogInformation("User logged out.");
            return RedirectToPage(returnUrl);
        }
    }
}

web-app/Pages/Account/PersonalInfo.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Reflection;
using System.Threading.Tasks;
using DAL.EF;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace web_app.Pages.Account
{
    [Authorize(Roles = "Admin, User")]
    public class PersonalInfoModel : PageModel
    {
        private readonly SignInManager<SportsHubUser> _signInManager;
        private readonly UserManager<SportsHubUser> _userManager;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public PersonalInfoModel(
            UserManager<SportsHubUser> userManager,
            SignInManager<SportsHubUser> signInManager,
            IWebHostEnvironment webHostEnvironment)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _webHostEnvironment = webHostEnvironment;
        }


        [BindProperty]
        public PersonalModel InputPersonal { get; set; }
        [BindProperty]
        public PasswordModel InputPassword { get; set; }

        public string onLoadTab { get; set; }
        public class PersonalModel
        {
            [Required]
            [EmailAddress]
            [Display(Name = "EMAIL")]
            public string Email { get; set; }

            [Required]
            [Display(Name = "FIRST NAME")]
            public string FirstName { get; set; }

            [Required]
            [Display(Name = "LAST NAME")]
            public string LastName { get; set; }

            public string ProfilePicturePath { get; set; }

            public IFormFile PictureFile { get; set; }

        }
        public class PasswordModel
        {
            [Required]
            [DataType(DataType.Password)]
            [Display(Name = "CURRENT PASSWORD")]
            public string OldPassword { get; set; }

            [Required]
            [StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 6)]
            [DataType(DataType.Password)]
            [RegularExpression(@"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$",
         ErrorMessage = "Password must include 1 uppercase character,1 lowercase character,1 special symbol and 1 number")]
            [Display(Name = "NEW PASSWORD")]
            public string NewPassword { get; set; }

            [Required]
            [DataType(DataType.Password)]
            [Display(Name = "CONFIRM PASSWORD")]
            [RegularExpression(@"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$",
         ErrorMessage = "Password must include 1 uppercase character,1 lowercase character,1 special symbol and 1 number")]
            [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
            public string ConfirmPassword { get; set; }
        }
        private async Task LoadPersonalAsync(SportsHubUser user)
        {

            InputPersonal = new PersonalModel
            {
                Email = await _userManager.GetEmailAsync(user),
                FirstName = user.FirstName,
                LastName = user.LastName,
                ProfilePicturePath = user.ProfilePicturePath,
                PictureFile = null
            };
        }

        public async Task<IActionResult> OnGetAsync(string tab="personalInfo")
        {
            var user = await _userManager.GetUserAsync(User);
            onLoadTab = tab;
            if (user == null)
            {
                return NotFound($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
            }

            await LoadPersonalAsync(user);
            this.InputPassword = new PasswordModel();
            return Page();
        }

        public async Task<IActionResult> OnPostPersonalAsync()
        {

            var user = await _userManager.GetUserAsync(User);
            foreach (PropertyInfo prop in InputPassword.GetType().GetProperties())
            {
                ModelState.Remove(prop.Name);
            }
            if (user == null)
            {
                return NotFound($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
            }

            if (!ModelState.IsValid)
            {
                await LoadPersonalAsync(user);
                onLoadTab = "personalInfo";
                return Page();
            }

            if (InputPersonal.FirstName != user.FirstName)
            {
                user.FirstName = InputPersonal.FirstName;
            }
            if (InputPersonal.LastName != user.LastName)
            {
                user.LastName = InputPersonal.LastName;
            }
            var email = await _userManager.GetEmailAsync(user);
            if (InputPersonal.Email != email)
            {
                user.Email=InputPersonal.Email;
            }
            var newPath = UploadedFile(InputPersonal);
            if (newPath != user.ProfilePicturePath && InputPersonal.PictureFile!=null)
            {
                user.ProfilePicturePath = newPath;
            }
            await _userManager.UpdateAsync(user);
            await _signInManager.RefreshSignInAsync(user);
            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostPasswordAsync()
        {

            var user = await _userManager.GetUserAsync(User);
            foreach (PropertyInfo prop in InputPersonal.GetType().GetProperties())
            {
                ModelState.Remove(prop.Name);
            }
            if (user == null)
            {
                return NotFound($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
            }

            if (!ModelState.IsValid)
            {
                await LoadPersonalAsync(user);
                onLoadTab = "changePassword";
                return Page();
            }
            if (InputPassword.NewPassword == InputPassword.ConfirmPassword)
            {
                var changePasswordResult = await _userManager.ChangePasswordAsync(user, InputPassword.OldPassword, InputPassword.NewPassword);
                if (!changePasswordResult.Succeeded)
                {
                    foreach (var error in changePasswordResult.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                    return Page();
                }
            }
            else
            {
                ModelState.AddModelError(string.Empty, "New Password and Confirm Password don't match.");
            }

            await _signInManager.RefreshSignInAsync(user);
            return RedirectToPage();
        }


        private string UploadedFile(PersonalModel InputPersonal)
        {
            string uniqueFileName = null;

            if (InputPersonal.PictureFile != null)
            {
                string uploadsFolder = Path.Combine(_webHostEnvironment.WebRootPath, "uploads/profilePictures");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + InputPersonal.PictureFile.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    InputPersonal.PictureFile.CopyTo(fileStream);
                }
            }
            return uniqueFileName;
        }
    }
}

web-app/Pages/Account/Register.cshtml.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using DAL.EF;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace web_app.Pages.Account
{
    [AllowAnonymous]
    public class RegisterModel : PageModel
    {
        private readonly SignInManager<SportsHubUser> _signInManager;
        private readonly UserManager<SportsHubUser> _userManager;
        private readonly ILogger<RegisterModel> _logger;

        public RegisterModel(
            UserManager<SportsHubUser> userManager,
            SignInManager<SportsHubUser> signInManager,
            ILogger<RegisterModel> logger)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _logger = logger;
        }

        [BindProperty]
        public InputModel Input { get; set; }

        public string ReturnUrl { get; set; }

        public IList<AuthenticationScheme> ExternalLogins { get; set; }

        public class InputModel
        {
            [Display(Name = "Name")]
            public string FirstName { get; set; }

            [Display(Name = "Last Name")]
            public string LastName { get; set; }

            [Required]
            [EmailAddress(ErrorMessage = "Please enter valid email")]
            [Display(Name = "Email")]
            public string Email { get; set; }

            [Required]
            [MinLength(8, ErrorMessage = "The {0} must be at least {1} characters long")]
            [RegularExpression("(?=.*[0-9])(?=.*[a-zA-Z])(.+)", ErrorMessage = "Password must contain at least 8 characters (letters and numbers)")]
            [DataType(DataType.Password)]
            [Display(Name = "Password")]
            public string Password { get; set; }
        }

        private void SetViewData()
        {
            ViewData["Title"] = "Register";
            ViewData["OtherOptionSpan"] = "Already have an account?";
            ViewData["OtherOptionLink"] = "/Account/Login";
            ViewData["OtherOption"] = "Log In";
        }

        public async Task OnGetAsync(string returnUrl = null)
        {
            ReturnUrl = returnUrl;
            SetViewData();
        }

        public async Task<IActionResult> OnPostAsync(string returnUrl = null)
        {
            returnUrl ??= Url.Content("~/Account/Login");
            if (ModelState.IsValid)
            {
                //Adjusted Register with default values for SportsHubUser
                var user = new SportsHubUser { UserName = Input.Email, Email = Input.Email, FirstName=Input.FirstName, LastName=Input.LastName, ProfilePicturePath="defaultProfilePicture.jpg" };
                var result = await _userManager.CreateAsync(user, Input.Password);
                if (result.Succeeded)
                {
                    _logger.LogInformation("User created a new account with password.");
                    
                    await _userManager.AddToRoleAsync(user, "User");
                    await _signInManager.SignInAsync(user, isPersistent: false);
                    return LocalRedirect(returnUrl);
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
            }

            SetViewData();
            return Page();
        }
    }
}

web-app/Pages/Account/Login.cshtml
@page
@model LoginModel
 
@{
    Layout = "_AuthorizeLayout";
}

<div class="d-flex align-items-center h-custom-2 px-5 mt-5 pt-5">
    <form asp-route-returnUrl="@Model.ReturnUrl" method="post" class="w-50">
        <h2 class="mb-3 pb-1 px-3">Log in to Sports Hub</h2>
        <div class="row row-cols-auto px-3 pb-3">
            <div class="col">
                <img src="~/images/FB.svg" alt="FaceBook logo"/>
                <img class="px-1" src="~/images/Gmail.svg" alt="Gmail logo"/>
            </div>
        </div> 
        <div class="col-sm-10">
            <label asp-for="Input.Email" class="label-font">Email Address</label>
            <input asp-for="Input.Email" type="email" class="form-control placeholder-custom rounded-0"
                    placeholder="Email@gmail.com"
                    required/>
        </div>
        <div class="col-sm-10 pt-2">
            <div class="row">
                <div class="col-sm-6">
                    <label asp-for="Input.Password" class="label-font">password</label>
                </div>
                <div class="col-sm-6 text-right">
                    <a href="" class="font-standart">Forgot password?</a>
                </div>
            </div>
            <input asp-for="Input.Password" class="form-control rounded-0"
                    placeholder="8 + characters (letters and numbers)"
                    pattern="(?=.*[0-9])(?=.*[a-zA-Z])(.+)" minlength="8"
                    required/>
        </div>
        <div asp-validation-summary=All class="text-danger"></div>
        <div class="col-sm-10 pt-2">
            <button type="submit" class="button-general red-button-filled rounded-0 w-100 btn-lg">LOG IN</button>
        </div>
    </form>
</div>

web-app/Pages/Account/Logout.cshtml
@page
@model LogoutModel
@{
    ViewData["Title"] = "Log out | Sports Hub";
}
 
<p>Logging out...</p>

web-app/Pages/Account/PersonalInfo.cshtml
@page 
@model PersonalInfoModel

<link rel="stylesheet" href="~/css/personalInfoStyle.css" asp-append-version="true" />


<div class=" mx-auto w-50 mb-5">
    <ul class="nav nav-tabs nav-fill nav-personal w-100 mb-5" role="group" aria-label="Basic radio toggle button group">
        <li class="nav-item" >
            <a class="nav-link" data-toggle="tab" href="#personalInfo"  role="tab" aria-controls="personalInfo" aria-selected="true">Personal</a>
        </li>
            
        <li class="nav-item" >
            <a class="nav-link" data-toggle="tab" href="#changePassword"  role="tab" aria-controls="changePassword" aria-selected="true">Change password</a>
        </li>
            
        <li class="nav-item" >
            <a class="nav-link disabled" data-toggle="tab" href="#mySurveys"  role="tab" aria-controls="mySurveys" aria-selected="false">My surveys</a>
        </li>

        <li class="nav-item" >
            <a class="nav-link disabled" data-toxggle="tab" href="#teamHub"  role="tab" aria-controls="teamHub" aria-selected="false">Team hub</a>
        </li>
    </ul>

    <div class="tab-content">
        <div class="tab-pane w-50 mx-auto mt-1" id="personalInfo" role="tabpanel" aria-labelledby="personalInfo-tab"> 
            <form enctype="multipart/form-data" asp-page-handler="Personal" method="post">
                <div asp-validation-summary="ModelOnly" id="_personalInfo" class="d-block mx-auto w-50"></div>
                <div class="form-group mb-4 w-25 mx-auto">
                    <input asp-for="InputPersonal.PictureFile" class="form-control" id="formFile" type="file" hidden accept=".jpg, .jpeg, .png">
                    <label for="formFile" class="rounded-circle">
                        <img src="~/uploads/profilePictures/@Model.InputPersonal.ProfilePicturePath" class="rounded-circle img-lg" height="40" width="40" asp-append-version="true" />
                        <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="white" class="bi bi-camera-fill rounded-circle" viewBox="0 0 15 20">
                            <path d="M10.5 8.5a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0z"/>
                            <path d="M2 4a2 2 0 0 0-2 2v6a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V6a2 2 0 0 0-2-2h-1.172a2 2 0 0 1-1.414-.586l-.828-.828A2 2 0 0 0 9.172 2H6.828a2 2 0 0 0-1.414.586l-.828.828A2 2 0 0 1 3.172 4H2zm.5 2a.5.5 0 1 1 0-1 .5.5 0 0 1 0 1zm9 2.5a3.5 3.5 0 1 1-7 0 3.5 3.5 0 0 1 7 0z"/>
                        </svg>
                    </label>
                </div>
                <div class="form-group mb-4">
                    <label asp-for="InputPersonal.FirstName" class="form-label"></label>
                    <input asp-for="InputPersonal.FirstName" class="form-control-plaintext" id="firstName">
                    <span asp-validation-for="InputPersonal.FirstName" class="text-danger"></span>
                </div>
                <div class="form-group mb-4">
                    <label asp-for="InputPersonal.LastName" class="form-label"></label>
                    <input asp-for="InputPersonal.LastName" class="form-control-plaintext" id="lastName">
                    <span asp-validation-for="InputPersonal.LastName" class="text-danger"></span>
                </div>
                <div class="form-group mb-4">
                    <label asp-for="InputPersonal.Email" class="form-label"></label>
                    <input asp-for="InputPersonal.Email" class="form-control-plaintext" id="email">
                    <span asp-validation-for="InputPersonal.Email" class="text-danger"></span>
                </div>
                <input type="submit" class="submit btn btn-primary mb-4 w-100" value="UPDATE PROFILE">
            </form>  
        </div>  
        <div class="tab-pane w-50 mx-auto mt-3" id="changePassword" role="tabpanel" aria-labelledby="changePassword-tab">  
            <form enctype="multipart/form-data" asp-page-handler="Password" method="post">  
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group mb-4">
                    <label asp-for="InputPassword.OldPassword" class="form-label"></label>
                    <input asp-for="InputPassword.OldPassword" class="form-control-plaintext" />
                    <span asp-validation-for="InputPassword.OldPassword" class="text-danger"></span>
                </div>
                <div class="form-group mb-4">
                    <label asp-for="InputPassword.NewPassword" class="form-label"></label>
                    <input asp-for="InputPassword.NewPassword" class="form-control-plaintext" />
                    <span asp-validation-for="InputPassword.NewPassword" class="text-danger"></span>
                </div>
                <div class="form-group mb-4">
                    <label asp-for="InputPassword.ConfirmPassword" class="form-label"></label>
                    <input asp-for="InputPassword.ConfirmPassword" class="form-control-plaintext" />
                    <span asp-validation-for="InputPassword.ConfirmPassword" class="text-danger"></span>
                </div>
                <input type="submit" class="submit btn btn-primary mb-4 w-100" value="UPDATE PASSWORD">
            </form>  
        </div>
        <div class="tab-pane w-50 mx-auto" id="mySurveys" role="tabpanel" aria-labelledby="mySurveys-tab">
        </div>
        <div class="tab-pane w-50 mx-auto" id="teamHub" role="tabpanel" aria-labelledby="teamHub-tab">  
        </div>
    </div>
</div>
<script>
var onLoadTab = @Model.onLoadTab;
onLoadTab.classList.add("active")
var links=[...document.getElementsByClassName("nav-link")]
links.filter(x => x.getAttribute("aria-controls")==onLoadTab.id)[0].classList.add("active")
</script>

web-app/Pages/Account/Register.cshtml
@page
@model RegisterModel

@{
    Layout = "_AuthorizeLayout";
}

<div class="d-flex align-items-center h-custom-2 px-5 mt-5 pt-5">
    <form asp-route-returnUrl="@Model.ReturnUrl" method="post">
        <h2 class="mb-3 pb-1 px-3">Create Account</h2>
        <div class="row row-cols-auto px-3 pb-3">
            <div class="col">
                <img src="~/images/FB.svg" alt="FaceBook logo"/>
                <img class="px-1" src="~/images/Gmail.svg" alt="Gmail logo"/>
            </div>
        </div>
        <span class="px-3 font-standart" style="color: #7F7B7B">Or use your email for registration:</span>
        <div class="row px-3 pt-3">
            <div class="col-sm-5 pt-2">
                <label asp-for="Input.FirstName" class="label-font">first name</label>
                <input asp-for="Input.FirstName" class="form-control rounded-0" placeholder="John" required />
            </div>
            <div class="col-sm-5 pt-2">
                <label asp-for="Input.LastName" class="label-font">last name</label>
                <input asp-for="Input.LastName" class="form-control rounded-0" placeholder="Doe" required />
            </div>
        </div>
        <div class="col-sm-10 pt-2">
            <label asp-for="Input.Email" class="label-font">email</label>
            <input asp-for="Input.Email" type="email" class="form-control rounded-0"
                    placeholder="johndoe@gmail.com"
                    required/>
        </div>
        <div class="col-sm-10 pt-2">
            <label asp-for="Input.Password" class="label-font">password</label>
            <input asp-for="Input.Password" class="form-control rounded-0"
                    placeholder="8 + characters (letters and numbers)"
                    pattern="(?=.*[0-9])(?=.*[a-zA-Z])(.+)" minlength="8"
                    required/>
        </div>
        <div asp-validation-summary=All class="text-danger"></div>
        <div class="col-sm-10 pt-2">
            <button type="submit" class="button-general red-button-filled rounded-0 w-100 btn-lg">SIGN UP</button>
        </div>
    </form>
</div>

web-app/Pages/Account/_AuthorizeLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewData["Title"] | Sports Hub</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/login-create-account.css" />
    <link rel="stylesheet" href="~/css/homePageLayout.css" />
    <script src="https://kit.fontawesome.com/eeab3bceea.js" crossorigin="anonymous" asp-append-version="true"></script>
</head>
<body>
    <div>
        <section class="vh-100">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-sm-5 px-0 d-none d-sm-block">
                        <img src="~/images/account-banner.jpg" alt="Login image" class="w-100 vh-100"
                                style="object-fit: cover; object-position: left;">
                        <div class="sticky-top position-absolute bg-custom px-4 py-2">
                            <span class="text-white">Sports Hub</span>
                        </div>
                    </div>
                    <div class="col-sm-7 text-black">
                        <div class="row pt-3">
                            <div class="col-sm-7 text-right my-auto">
                                <span class="text-muted font-standart">@ViewData["OtherOptionSpan"]</span>
                            </div>
                            <div class="col-sm-5">
                                <a asp-page=@ViewData["OtherOptionLink"] class="btn button-general button-white rounded-0 shadow-none">
                                    @ViewData["OtherOption"]
                                </a>
                            </div>
                        </div>
                        @RenderBody()
                    </div>
                </div>
            </div>
        </section>
    </div>
</body>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

</html>