web-app/Controllers/LanguagesController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Localization;

namespace web_app.Controllers
{
    public class LanguagesController : Controller
    {
        [HttpPost]
        public IActionResult SetLanguage(string culture)
        {
            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
            );

            return Redirect(Request.Headers["Referer"].ToString());
        }
    }
}

web-app/Pages/Shared/_ArticleLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width" />

    <title>@ViewBag.Title</title>

    <link rel="stylesheet" href="~/articles/bootstrap5/css/bootstrap.css">
    <link rel="stylesheet" href="~/articles/font-awesome-4.7.0/css/font-awesome.min.css">

    <link href="~/css/homePageLayout.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/css/informationArchitecture.css" rel="stylesheet" asp-append-version="true" />
    <link rel="stylesheet" href="~/articles/bootstrap5/css/articleEdit.min.css">
    <link rel="stylesheet" href="~/articles/bootstrap5/css/articleView.min.css">


    <!-- Google Fonts -->
    <script src="https://kit.fontawesome.com/eeab3bceea.js" crossorigin="anonymous" asp-append-version="true"></script>

    <!-- Font Awesome Fonts -->
    <script src="https://kit.fontawesome.com/6df1037d80.js" crossorigin="anonymous"></script>

    <!-- Tiny cloud text editor -->
    <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>


    <script>
        tinymce.init({
            forced_root_block: "p",
            selector: 'textarea#editor',
            skin: 'bootstrap',
            plugins: 'lists, link, image, media',
            toolbar: 'h1 h2 P bold italic underline | alignleft aligncenter alignright alignjustify  | link image media ',
            menubar: false
        });
    </script>

</head>
<body>


    <partial name="_HeaderPartial" />
    <div id="title-container"></div>
    <div class="container-fluid under-header">
        <div class="row">
            <partial name="_NavigationPartial" />
            <main role="main" class="pb-3 col content">
                @this.RenderBody()
            </main>
        </div>
    </div>

    <partial name="_FooterPartial" />




    @*for image preview*@
    <script>
        const inpFile = document.getElementById("inpFile");
        const previewContainer = document.getElementById("imagePreview");
        const previewImage = previewContainer.querySelector(".image-preview__image");
        const previewDefaultText = previewContainer.querySelector(".image-preview__default-text");

        inpFile.addEventListener("change", function () {
            const file = this.files[0];

            if (file) {
                const reader = new FileReader()
                previewDefaultText.style.display = "none";
                previewImage.style.display = "block";

                reader.addEventListener("load", function () {
                    console.log(this);
                    previewImage.setAttribute("src", this.result);
                    Article.PictureUrl = this.result; /* set picture url to article*/
                });
                reader.readAsDataURL(file);
            }
            else {
                previewDefaultText.style.display = null; /* use css default values */
                previewImage.style.display = null;
            }
        });

    </script>

    <script>
        const inpFile = document.getElementById("inpFile");
        const previewContainer = document.getElementById("imagePreview");
        const previewImage = previewContainer.querySelector(".image-preview__image");
        const previewDefaultText = previewContainer.querySelector(".image-preview__default-text");

        inpFile.addEventListener("change", function () {
            const file = this.files[0];

            if (file) {
                const reader = new FileReader();
                previewDefaultText.style.display = "none";
                previewImage.style.display = "block";

                reader.addEventListener("load", function () {
                    console.log(this);
                    previewImage.setAttribute("src", this.result);

                });
                reader.readAsDataURL(file);
            }
        });
    </script>


    <script src="~/articles/bootstrap5/js/bootstrap.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/signalr/dist/browser/signalr.min.js"></script>


    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
            integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.6.0/umd/popper.min.js"
            integrity="sha512-BmM0/BQlqh02wuK5Gz9yrbe7VyIVwOzD1o40yi1IsTjriX/NGF37NyXHfmFzIlMmoSIBXgqDiG1VNU6kB5dBbA=="
            crossorigin="anonymous"></script>

    @await this.RenderSectionAsync("Scripts", required: false)
</body>
</html>

web-app/Pages/Shared/_FooterPartial.cshtml
@using Microsoft.AspNetCore.Mvc.Localization

@inject IViewLocalizer Localizer

<footer class="container-fluid">
    <div class="footer-info row">
        <div class="col-3 footer-info-first-child">
            <h3>@Localizer["Company Info"]</h3>
            <ul>
                <li>
                    <a href="#">@Localizer["About Sports Hub"]</a>
                </li>
                <li>
                    <a href="#">@Localizer["News / In the Press"]</a>
                </li>
                <li>
                    <a href="#">@Localizer["Advertising / Sports Blogger Ad Network"]</a>
                </li>
                <li>
                    <a href="#">@Localizer["Events"]</a>
                </li>
                <li>
                    <a href="#">@Localizer["Contact Us"]</a>
                </li>
            </ul>
        </div>
        <div class="col-3">
            <h3>@Localizer["Contributors"]</h3>
            <ul>
                <li>
                    <a href="#">@Localizer["Featured Writers Program"]</a>
                </li>
                <li>
                    <a href="#">@Localizer["Featured Team Writers Program"]</a>
                </li>
                <li>
                    <a href="#">@Localizer["Internship Program"]</a>
                </li>
            </ul>
        </div>
        <div class="col-3">
            <h3>@Localizer["Newsletter"]</h3>
            <ul>
                <li>
                    <p>@Localizer["Sign up to receive the latest sports news"]</p>
                    <form action="" class="newsletter-form">
                        <input type="email" class="email-input" placeholder="@Localizer["Your email address"]">
                        <button class="red-button-filled">@Localizer["Subscribe"]</button>
                    </form>
                </li>
            </ul>
        </div>
        <div class="col w-7"></div>
    </div>
    <div class="footer-copyright row">
        <div class="logo w-18 col-3">
            <h2 class="h2-layout">Sports Hub</h2>
        </div>
        <div class="copyright-and-terms col">
            <ul>
                <li>
                    <p>Copyright ©2019 Sports Hub</p>
                </li>
                <li>
                    <a href="#">@Localizer["Privacy / Terms"]</a>
                </li>
            </ul>
        </div>
    </div>
</footer>

web-app/Pages/Shared/_HeaderPartial.cshtml
@using Microsoft.AspNetCore.Mvc.Localization

@inject IViewLocalizer Localizer

<header class="container-fluid text-center">
    <div class="row h-100">
        <div class="col logo w-18">
            <h2>Sports Hub</h2>
        </div>
        <div class="col search">
            <i class="fa-solid fa-magnifying-glass"></i>
            <form asp-page="/Search" method="post" defaultButton="SubmitButton" class="search-form">
                <input name="SearchString" type="text" class="search-form-input" 
                       placeholder="@Localizer["Search by"]" 
                       value=@ViewData["SearchString"]
                       required>
            </form>
        </div>
        <div class="col share">
            <p class="share-text">@Localizer["Share"]</p>
            <ul class="container share-icons link-icons">
                <li>
                    <a href="#"><i class="fa-brands fa-facebook-f"></i></a>
                </li>
                <li>
                    <a href="#"><i class="fa-brands fa-twitter"></i></a>
                </li>
                <li>
                    <a href="#"><i class="fa-brands fa-google-plus-g"></i></a>
                </li>
            </ul>
        </div>
        <div class="col authentication">
            <ul class="auth-items">
                <partial name="_LoginPartial" />
                <partial name="_SelectLanguagePartial" />
            </ul>
        </div>
    </div>
</header>

web-app/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Css Styles -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous" asp-append-version="true" />
    <link href="~/css/homePageLayout.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/css/informationArchitecture.css" rel="stylesheet" asp-append-version="true" />

    <!-- Google Fonts -->
    <script src="https://kit.fontawesome.com/eeab3bceea.js" crossorigin="anonymous" asp-append-version="true"></script>

    <title>@this.ViewData["Title"]</title>
</head>
<body>
    <partial name="_HeaderPartial" />
    <div id="title-container"></div>
    <div class="container-fluid under-header">
        <div class="row">
            <partial name="_NavigationPartial" />
            <main role="main" class="pb-3 col content">
              @this.RenderBody()
            </main>
        </div>
    </div>

    <partial name="_FooterPartial" />

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/signalr/dist/browser/signalr.min.js"></script>

    @await this.RenderSectionAsync("Scripts", required: false)
</body>
</html>

web-app/Pages/Shared/_NavigationPartial.cshtml
@using Microsoft.AspNetCore.Mvc.Localization

@inject IViewLocalizer Localizer

<nav class="col nav w-18">
    <div>
        <ul class="nav-sections-list">
            <li class="nav-item">
                <a asp-area="" asp-page="Articles/Articles">@Localizer["Articles"]</a>
            </li>

            <li>
                <a href="#">@Localizer["Home"]</a>
            </li>
            <li>
                <a href="#">NBA</a>
            </li>
            <li>
                <a href="#">NFL</a>
            </li>
            <li>
                <a href="#">MLB</a>
            </li>
            <li>
                <a href="#">NHL</a>
            </li>
            <li>
                <a href="#">CBB</a>
            </li>
            <li>
                <a href="#">CFB</a>
            </li>
            <li>
                <a href="#">NASCAR</a>
            </li>
            <li>
                <a href="#">@Localizer["Golf"]</a>
            </li>
            <li>
                <a href="#">@Localizer["Soccer"]</a>
            </li>
            <li>
                <a href="#">@Localizer["Team Hub"]</a>
            </li>
            <li>
                <a href="#">@Localizer["Lifestyle"]</a>
            </li>
            <li>
                <a href="#">@Localizer["Dealbook"]</a>
            </li>
            <li>
                <a href="/Videos/Video">@Localizer["Video"]</a>
            </li>
        </ul>
    </div>
    <div class="nav-icons row">
        <p class="nav-follow">@Localizer["Follow"]</p>
        <ul class="container nav-icons-list">
            <div class="row upper-icons link-icons">
            <li class="col">
                <a href="#"><i class="fa-brands fa-facebook-f"></i></a>
            </li>
            <li class="col">
                <a href="#"><i class="fa-brands fa-twitter"></i></a>
            </li>
    </div>
    <div class="row link-icons">
        <li class="col google-icon">
            <a href="#"><i class="fa-brands fa-google"></i></a>
        </li>
        <li class="col">
            <a href="#"><i class="fa-brands fa-youtube"></i></a>
        </li>
    </div>
    </ul>
    </div>
</nav>

web-app/Pages/Shared/_SelectLanguagePartial.cshtml
@using System.Threading.Tasks
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options

@inject IOptions<RequestLocalizationOptions> LocOptions

<script src="/lib/jquery/dist/jquery.js"></script>

@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultureItems = LocOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.Name.ToUpper() })
        .ToList();
}

<li>
    <!-- TODO: 180 degrees arrow and option items beautified -->
    <form id="selectLanguageForm" asp-controller="Languages" asp-action="SetLanguage" method="post">
        <select name="culture" id="selectLanguage" class="form-select font-standart shadow-none border-0" asp-for="@requestCulture.RequestCulture.UICulture.Name" asp-items="cultureItems"
            onchange="document.getElementById('selectLanguageForm').submit();">
        </select>
    </form>
</li>

<script>
    $(function () {
        $("#selectLanguage > option").addClass("bg-active-light-red font-standart");
    })
</script>