web-app/Pages/Videos/Video.cshtml.cs
using BAL.DTOs.Categories;
using BAL.Interfaces.Managers;
using DAL.EF;
using DAL.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Text.Json;
using System.Threading.Tasks;

namespace web_app.Pages.Video
{
    public class VideoPageModel : PageModel
    {
        private readonly UserManager<SportsHubUser> _userManager;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly ApplicationDbContext _context;
        private readonly ICategoryManager _categoryManager;


        public VideoPageModel(ICategoryManager categoryService,
            UserManager<SportsHubUser> userManager,
            IWebHostEnvironment webHostEnvironment,
            ApplicationDbContext context)
        {
            _categoryManager = categoryService;
            _userManager = userManager;
            _webHostEnvironment = webHostEnvironment;
            _context = context;
        }
        public class InputModel
        {
            public string VideoURL { get; set; }

            public IFormFile VideoFile { get; set; }

        }
        public class Filter
        {
            public string Name { get; set; }
            public PublishedSelector Published { get; set; } = PublishedSelector.All;

        }

        public enum PublishedSelector
        {
            All,
            Unpublished,
            Published
        };


        public IEnumerable<VideoModel> Videos { get; set; }

        private bool isLink = false;
        private string Title = "Default Title";
        public bool isPreview;
        public CategoriesIndexViewModel Categories;

        [BindProperty]
        public InputModel Input { get; set; }

        
        [BindProperty]
        public Filter Filters { get; set; } = new Filter();


        public async Task<IActionResult> OnGetAsync(string searchString,PublishedSelector publishedFilter,bool isPreview=false)
        {
            Filters.Name = searchString;
            Filters.Published = publishedFilter;
            this.isPreview = isPreview;
            var user= await LoadDataAsync(Filters);
            if (user == null)
            {
                return NotFound($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
            }
            return Page();
        }

        
        private async Task<SportsHubUser> LoadDataAsync(Filter Filters)
        {
            var user = await _userManager.GetUserAsync(User);
            Videos = await _context.Videos.ToListAsync();
            Videos = Videos.Reverse();
            Categories= new CategoriesIndexViewModel
            {
                Categories = _categoryManager.GetAllCategories<CategoryViewModel>().ToList(),
            };

            if (!String.IsNullOrEmpty(Filters.Name))
            {
                Videos = Videos.Where(x => x.Title.ToLower().Contains(Filters.Name.ToLower()));
            }
            if (Filters.Published!= PublishedSelector.All)
            {
                if (Filters.Published == PublishedSelector.Published)
                    Videos = Videos.Where(x => x.isPublished);
                else
                    Videos = Videos.Where(x => !x.isPublished);
            }
            return user;
        }

        //Redirecting to CreateVideo after submitting the New Video modal, passing the Video's url and wether it is a link or a file path

        public async Task<IActionResult> OnPostAsync()
        {
            if (User == null)
            {
                return NotFound($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
            }

            if (!ModelState.IsValid)
            {
                return Page();
            }

            if (!string.IsNullOrWhiteSpace(Input.VideoURL))
            {
                var data=await VideoData.GetData(Input.VideoURL);
                if (data.error != null)
                {
                    await LoadDataAsync(Filters);
                    ModelState.AddModelError("Input.VideoURL", "Invalid video (Video may not be authorized)");
                    return Page();
                }
                Input.VideoURL=ExtractCode(data.url);
                Title = data.title;
                isLink = true;
            }
            else if (Input.VideoFile != null)
            {
                Input.VideoURL = UploadedFile(Input.VideoFile, "uploads/videos", _webHostEnvironment);
            }
            else
            {
                await LoadDataAsync(Filters);
                return Page();
            }
            return RedirectToPage("VideoCreate", new VideoModel{ URL=Input.VideoURL,Title=Title,IsLink=isLink });
        }

        public async Task<IActionResult> OnPostDeleteAsync(int id)
        {
            var video=await _context.Videos.FindAsync(id);
            _context.Videos.Remove(video);
            _context.SaveChanges();
            await LoadDataAsync(Filters);
            return Page();
        }
        public async Task<IActionResult> OnPostPublishAsync(int id)
        {
            var video = await _context.Videos.FindAsync(id);
            video.isPublished = !video.isPublished;
            video.PublishDate = DateTime.Now;
            _context.Videos.Update(video);
            _context.SaveChanges();
            await LoadDataAsync(Filters);
            return Page();
        }

        //Uploads the selected file with generated code in a certain foulder 
        public static string UploadedFile(IFormFile file, string foulderPath,IWebHostEnvironment _webhost)
        {
            string uniqueFileName = null;

            if (file != null)
            {
                string uploadsFolder = Path.Combine(_webhost.WebRootPath, foulderPath);
                uniqueFileName = Guid.NewGuid().ToString() + file.FileName[file.FileName.LastIndexOf('.')..];
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using var fileStream = new FileStream(filePath, FileMode.Create);
                file.CopyTo(fileStream);
            }
            return uniqueFileName;
        }

        //Extracts the Youtube id of a youtube link
        public static string ExtractCode(string url)
        {
            return url[(url.LastIndexOf("watch?v=") + 8)..];
        }

    }
}

web-app/Pages/Videos/VideoCreate.cshtml.cs
using BAL.DTOs.Categories;
using BAL.Interfaces.Managers;
using DAL.EF;
using DAL.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Reflection;
using System.Text.Json;
using System.Threading.Tasks;

namespace web_app.Pages.Video
{
    [Authorize(Roles = "Admin")]
    public class VideoCreateModel : PageModel
    {
        private readonly UserManager<SportsHubUser> _userManager;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly ApplicationDbContext _context;
        private readonly ICategoryManager _categoryManager;


        public VideoCreateModel(ICategoryManager categoryService,
            UserManager<SportsHubUser> userManager,
            IWebHostEnvironment webHostEnvironment,
            ApplicationDbContext context)
        {
            _categoryManager = categoryService;
            _userManager = userManager;
            _webHostEnvironment = webHostEnvironment;
            _context = context;
        }
        public class InputModel
        {
            public string VideoURL { get; set; }

            public IFormFile VideoFile { get; set; }

        }

        [BindProperty]
        public InputModel Input { get; set; }
        [BindProperty]
        public VideoModel CurrentVideo { get; set; }
        public CategoriesIndexViewModel Categories { get; private set; }

        public IActionResult OnGet(VideoModel video)
        {
            CurrentVideo = video;
            Categories = new CategoriesIndexViewModel
            {
                Categories = _categoryManager.GetAllCategories<CategoryViewModel>().ToList(),
            };
            return Page();
        }

        public virtual async Task<IActionResult> OnPostAsync()
        {
            if (User == null)
                return NotFound($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");

            Categories = new CategoriesIndexViewModel
            {
                Categories = _categoryManager.GetAllCategories<CategoryViewModel>().ToList(),
            };

            if (!string.IsNullOrWhiteSpace(Input.VideoURL))
            {
                var data = await VideoData.GetData(Input.VideoURL);
                if (data.error != null)
                {
                    Input.VideoURL = "";
                    ModelState.AddModelError("Input.VideoURL", "Invalid video (Video may not be authorized)");
                    return Page();
                }
                CurrentVideo.URL = VideoPageModel.ExtractCode(data.url);
                CurrentVideo.Title = data.title;
                CurrentVideo.IsLink = true;
            }
            else if (Input.VideoFile != null)
            {
                CurrentVideo.URL = VideoPageModel.UploadedFile(Input.VideoFile, "uploads/videos", _webHostEnvironment);
                CurrentVideo.IsLink = false;
                CurrentVideo.Title = "Set Title";
            }
            return Page();
        }
        public virtual async Task<IActionResult> OnPostSaveAsync()
        {
            var user = await _userManager.GetUserAsync(User);
            if (User == null)
                return NotFound($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");

            if (!ModelState.IsValid)
                return Redirect(Request.Path);


            CurrentVideo.Uploader = user;
            CurrentVideo.isPublished = false;

            await _context.Videos.AddAsync(CurrentVideo);
            await _context.SaveChangesAsync();
            return RedirectToPage("Video");
        }

    }
}

web-app/Pages/Videos/VideoDetails.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using DAL.EF;
using DAL.Models;
using Microsoft.AspNetCore.Identity;

namespace web_app.Pages.Videos
{
    public class VideoDetailsModel : PageModel
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<SportsHubUser> _userManager;


        public VideoDetailsModel(ApplicationDbContext context,UserManager<SportsHubUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public List<VideoModel> Videos { get; private set; }
        public VideoModel VideoModel { get; set; }
        [BindProperty]
        public string Comment { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Videos = await _context.Videos.ToListAsync();
            VideoModel = await _context.Videos.Include(x=>x.Coments).ThenInclude(x=>x.Uploader).Include(x=>x.Uploader).FirstOrDefaultAsync(m => m.Id == id);
            if (VideoModel == null)
            {
                return NotFound();
            }
            VideoModel.Views++;
            _context.Videos.Update(VideoModel);
            await _context.SaveChangesAsync();
            return Page();
        }
        public async Task<IActionResult> OnPostAsync(int? id)
        {
            var user = await _userManager.GetUserAsync(User);
            if (User == null)
                return NotFound($"Unable to load user with ID '{user.Id}'.");

            Videos = await _context.Videos.ToListAsync();
            VideoModel = await _context.Videos.Include(x => x.Coments).ThenInclude(x => x.Uploader).Include(x => x.Uploader).FirstOrDefaultAsync(m => m.Id == id);
            VideoModel.Coments.Add(new ComentsModel() { Uploader = user, Details = Comment, PublishDate = DateTime.Now });
            _context.Videos.Update(VideoModel);
            await _context.SaveChangesAsync();
            return Page();
        }
        public async Task<IActionResult> OnPostDeleteAsync(int? id,int? commentID)
        {
            var user = await _userManager.GetUserAsync(User);
            if (User == null)
                return NotFound($"Unable to load user with ID '{user.Id}'.");

            Videos = await _context.Videos.ToListAsync();
            VideoModel = await _context.Videos.Include(x => x.Coments).ThenInclude(x => x.Uploader).Include(x => x.Uploader).FirstOrDefaultAsync(m => m.Id == id);
            var DeletedComment = VideoModel.Coments.FirstOrDefault(m => m.Id == commentID);

            _context.Comments.Remove(DeletedComment);
            VideoModel.Coments.Remove(DeletedComment);
            _context.Videos.Update(VideoModel);
            await _context.SaveChangesAsync();
            return Page();
        }
    }
}

web-app/Pages/Videos/VideoEdit.cshtml.cs
using BAL.DTOs.Categories;
using BAL.Interfaces.Managers;
using DAL.EF;
using DAL.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Reflection;
using System.Text.Json;
using System.Threading.Tasks;

namespace web_app.Pages.Video
{
    [Authorize(Roles = "Admin")]
    public class VideoEditModel : PageModel
    {
        private readonly UserManager<SportsHubUser> _userManager;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly ApplicationDbContext _context;
        private readonly ICategoryManager _categoryManager;


        public VideoEditModel(ICategoryManager categoryService,
            UserManager<SportsHubUser> userManager,
            IWebHostEnvironment webHostEnvironment,
            ApplicationDbContext context)
        {
            _categoryManager = categoryService;
            _userManager = userManager;
            _webHostEnvironment = webHostEnvironment;
            _context = context;
        }

        public class InputModel
        {
            public string VideoURL { get; set; }

            public IFormFile VideoFile { get; set; }

        }

        [BindProperty]
        public InputModel Input { get; set; }
        [BindProperty]
        public VideoModel CurrentVideo { get; set; }
        public CategoriesIndexViewModel Categories { get; private set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            CurrentVideo = await _context.Videos.FindAsync(id);
            if (CurrentVideo == null)
                return NotFound();
            Categories = new CategoriesIndexViewModel
            {
                Categories = _categoryManager.GetAllCategories<CategoryViewModel>().ToList(),
            };
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (User == null)
                return NotFound($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");

            if (!string.IsNullOrWhiteSpace(Input.VideoURL))
            {
                var data = await VideoData.GetData(Input.VideoURL);
                if (data.error != null)
                {
                    Input.VideoURL = "";
                    ModelState.AddModelError("Input.VideoURL", "Invalid video (Video may not be authorized)");
                    return Page();
                }
                CurrentVideo.URL = VideoPageModel.ExtractCode(data.url);
                CurrentVideo.Title = data.title;
                CurrentVideo.IsLink = true;
            }
            else if (Input.VideoFile != null)
            {
                CurrentVideo.URL = VideoPageModel.UploadedFile(Input.VideoFile, "uploads/videos", _webHostEnvironment);
                CurrentVideo.IsLink = false;
                CurrentVideo.Title = "Set Title";
            }
            return Page();
        }
        public async Task<IActionResult> OnPostSaveAsync()
        {
            var user = await _userManager.GetUserAsync(User);
            if (User == null)
                return NotFound($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");

            if (!ModelState.IsValid)
                return Redirect(Request.Path);


            CurrentVideo.Uploader = user;
            CurrentVideo.isPublished = false;

            _context.Videos.Update(CurrentVideo);
            await _context.SaveChangesAsync();
            return RedirectToPage("Video");
        }

    }
}

web-app/Pages/Videos/VideoCreate.cshtml
@page 
@model web_app.Pages.Video.VideoCreateModel
@{
    ViewData["Title"] = "Video";
    Layout = "_VideoLayout.cshtml";
}
<link rel="stylesheet" href="~/css//video.css" asp-append-version="true" />
<div class="preview-container">
    <form enctype="multipart/form-data" method="post" asp-page-handler="Save">
        <button id="submit-video" type="submit" hidden></button>
        <div class="video-preview" >
                @if(Model.CurrentVideo.IsLink){
                    <iframe id="video-preview"  src="https://www.youtube.com/embed/@Model.CurrentVideo.URL?rel=0&amp;autoplay=1&mute=1"></iframe>
                }
                else
                {
                    <video autoplay muted id="video-preview"> <source src="~/uploads/videos/@Model.CurrentVideo.URL"> </video>
                }
                <div id="video-overlay" >
                    <div class="upper-right control rounded-circle">
                        <a class="control-text" href="Video">
                            <svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="20" height="20" viewBox="0 0 30 30" style=" fill:#FFFFFF;">
                                <path d="M 13 3 A 1.0001 1.0001 0 0 0 11.986328 4 L 6 4 A 1.0001 1.0001 0 1 0 6 6 L 24 6 A 1.0001 1.0001 0 1 0 24 4 L 18.013672 4 A 1.0001 1.0001 0 0 0 17 3 L 13 3 z M 6 8 L 6 24 C 6 25.105 6.895 26 8 26 L 22 26 C 23.105 26 24 25.105 24 24 L 24 8 L 6 8 z"></path>
                            </svg>
                        </a>            
                    </div>
                    <div class="center control rounded-circle" data-toggle="modal" data-target="#videoModal">
                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" style=" fill:#FFFFFF;" viewBox="0 0 24 24">
                            <path d="M16 16c0 1.104-.896 2-2 2h-12c-1.104 0-2-.896-2-2v-8c0-1.104.896-2 2-2h12c1.104 0 2 .896 2 2v8zm8-10l-6 4.223v3.554l6 4.223v-12z"/>
                         </svg>
                    </div>
                </div>
        </div>
        <span asp-validation-for="Input.VideoURL" class="text-danger"></span>
        <input asp-for="CurrentVideo.Id" class="form-control-plaintext" hidden id="ID">
        <input asp-for="CurrentVideo.URL" class="form-control-plaintext" hidden id="URL">
        <input asp-for="CurrentVideo.Uploader" class="form-control-plaintext" hidden id="Uploader">
        <input asp-for="CurrentVideo.IsLink" class="form-control-plaintext" hidden id="isLink">
        <br />
        <div class="mb-4 w-100">
            <label asp-for="CurrentVideo.Title" class="form-label">Title</label>
            <input asp-for="CurrentVideo.Title" class="form-control-plaintext" id="Title" >
            <span asp-validation-for="CurrentVideo.Title" class="text-danger"></span>
        </div>
        <div class="mb-4 w-100">
            <label asp-for="CurrentVideo.Comments" class="form-label"></label>
            <input asp-for="CurrentVideo.Comments" class="form-control-plaintext" id="Comments" >
            <span asp-validation-for="CurrentVideo.Comments" class="text-danger"></span>
        </div> 
    </form>
</div>
<form enctype="multipart/form-data" method="post">
    <div id="videoModal" class="modal" tabindex="-1" role="dialog">
        <div class="modal-dialog mt-5" role="document">
            <div class="modal-content">
                <div class="modal-header mx-auto">
                    <h5 class="modal-title">Add new video</h5>
                </div>
                <div class="modal-body">
                    <div class="mb-4 w-100">
                        <label asp-for="Input.VideoURL" class="form-label">ADD LINK</label>
                        <input asp-for="Input.VideoURL" class="form-control-plaintext" id="firstName" placeholder="Add new link">
                        <span asp-validation-for="Input.VideoURL" class="text-danger"></span>
                    </div>
                    <div class="mb-4 w-100">
                        <label asp-for="Input.VideoURL" class="form-label w-100">UPLOAD</label>
                        <input asp-for="Input.VideoFile" class="form-control" id="formFile" type="file" hidden accept="video/*" >
                        <label for="formFile" class="d-flex rounded-0 flex-row">
                            <span id="file-chosen" class="form-control-plaintext">Upload new video</span>
                            <div class="btn btn-primary">UPLOAD</div>
                        </label>
                    </div>  
                    <div class="modal-footer w-100">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                        <button type="submit" class="btn btn-primary">Add</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </form>


<script>
    const fileChosen = document.getElementById('file-chosen');
    const actualBtn = document.getElementById('formFile');
    const titleElement = document.getElementById("title-container");
    var title = '<div class="d-inline-flex justify-content-between align-items-center w-100 title-bar"><h1>@ViewData["Title"]</h1><div></div></div>';
 
    if("True"=="@User.IsInRole("Admin")")
        title = '<div class="d-inline-flex justify-content-between align-items-center w-100 title-bar"><h1>@ViewData["Title"]</h1><div class="w-25"><a class="btn btn-secondary w-50" href="Video">Cancel</a><label class="btn btn-primary w-50" for="submit-video" tabindex="0">Save</label></div></div>';
        
    titleElement.innerHTML=title+titleElement.innerHTML;
    actualBtn?.addEventListener('change', function(){
        fileChosen.textContent = this.files[0].name
    })
</script>

web-app/Pages/Videos/_AdminVideoPartial.cshtml
@using web_app.Pages.Video
@model VideoPageModel 

<span asp-validation-for="Input.VideoURL" class="text-danger"></span>
<div class="list-container d-flex flex-wrap align-content-start h-100">
    <div class="w-100">
        <form asp-page="./Video" method="get">
            <div class="d-inline-flex justify-content-end w-100 mb-3 p-3">
                <div id="searchIcon" onclick="showSearchBar()">
                    <svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px"
                width="20" height="20"
                viewBox="0 0 30 30"
                style=" fill:#7F8899;"><path d="M 13 3 C 7.4889971 3 3 7.4889971 3 13 C 3 18.511003 7.4889971 23 13 23 C 15.396508 23 17.597385 22.148986 19.322266 20.736328 L 25.292969 26.707031 A 1.0001 1.0001 0 1 0 26.707031 25.292969 L 20.736328 19.322266 C 22.148986 17.597385 23 15.396508 23 13 C 23 7.4889971 18.511003 3 13 3 z M 13 5 C 17.430123 5 21 8.5698774 21 13 C 21 17.430123 17.430123 21 13 21 C 8.5698774 21 5 17.430123 5 13 C 5 8.5698774 8.5698774 5 13 5 z"></path></svg>
                </div>
            
                    <div id="searchBar">
                        <div class="form-actions no-color">
                            <label for="submitSearch" onclick="hideSearchBar()">
                                <svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px"
                            width="20" height="20"
                            viewBox="0 0 30 30"
                            style=" fill:#7F8899;"><path d="M 13 3 C 7.4889971 3 3 7.4889971 3 13 C 3 18.511003 7.4889971 23 13 23 C 15.396508 23 17.597385 22.148986 19.322266 20.736328 L 25.292969 26.707031 A 1.0001 1.0001 0 1 0 26.707031 25.292969 L 20.736328 19.322266 C 22.148986 17.597385 23 15.396508 23 13 C 23 7.4889971 18.511003 3 13 3 z M 13 5 C 17.430123 5 21 8.5698774 21 13 C 21 17.430123 17.430123 21 13 21 C 8.5698774 21 5 17.430123 5 13 C 5 8.5698774 8.5698774 5 13 5 z"></path></svg>
                            </label>
                            <input id="search" type="text" name="searchString" placeholder="Search..." onfocusout="hideSearchBar(2000)"  asp-for=Filters.Name />
                            <input id="submitSearch" type="submit" hidden/> 
                        </div>
                    </div>
            </div>
            <div class="d-inline-flex justify-content-between w-100 mb-3 p-3">
                <div class="dropdown-filter w-18">
                    <select class="btn dropdown-toggle w-100" onchange="this.form.submit()" name="publishedFilter" asp-for="Filters.Published" asp-items="Html.GetEnumSelectList<Video.VideoPageModel.PublishedSelector>()">
                    </select>
                
                </div>
                <div class="form-check form-switch align-items-center w-18">
                    <label class="form-check-label" for="flexSwitchCheckDefault">Allow to share videos:</label>
                    <input class="form-check-input" type="checkbox" id="flexSwitchCheckDefault">
                </div>
            </div>
        </form>
    </div>
    <div class="video-list w-100 p-3">
        <form method="post">
        @foreach (var item in Model.Videos)
        {
            <div class="video-info d-inline-flex justify-content-between w-100 h-auto">
                <div class="video-thumbnail">
                    @if (@item.IsLink)
                    {
                        <img class="thumbnail" src="https://img.youtube.com/vi/@item.URL/hqdefault.jpg"/>
                    }
                    else
                    {
                        <img class="thumbnail" src="/images/DefaultVideoPicture.jpeg"/>
                    }
                </div>
                <div class="video-details w-100">
                    <h2 class="video-title">@item.Title</h2>
                    <br>
                    @if (@item.isPublished)
                    {
                        <div class="d-inline-flex align-items-center"><div class="green-dot rounded-circle"></div>   Published</div>
                    }
                    else
                    {
                        <div class="d-inline-flex align-items-center"><div class="red-dot rounded-circle"></div>    Not Published</div>
                    }
                </div>
                <div class="dropdown">
                    <button class="detail-button" type="button" id="deleteDropdown" data-toggle="dropdown" aria-haspopup="false" aria-expanded="false">
                        ...
                    </button>
                    <div class="dropdown-menu" aria-labelledby="deleteDropdown">
                        @if (@item.isPublished)
                        {
                            <button class="btn-secondary border-0 dropdown-item" type="submit" asp-page-handler="Publish" asp-route-id="@item.Id" onclick="return confirm('Are you sure you want to unpublish?')" >Unpublish</button>
                        }
                        else
                        {
                            <button class="btn-secondary border-0 dropdown-item" type="submit" asp-page-handler="Publish" asp-route-id="@item.Id" onclick="return confirm('Are you sure you want to publish?')" >Publish</button>
                        }
                        <a class="btn-secondary border-0 dropdown-item" asp-page="VideoEdit" asp-route-id="@item.Id">Edit</a>
                        <a class="btn-secondary border-0 dropdown-item" asp-page="VideoDetails" asp-route-id="@item.Id">Details</a>
                        <button class="btn-secondary border-0 dropdown-item" type="submit" asp-page-handler="Delete" asp-route-id="@item.Id" onclick="return confirm('Are you sure you want to delete?')" >Delete</button>
                    </div>
                </div>
            </div>
        }
        </form>
    </div>
</div>
<form enctype="multipart/form-data" method="post">
    <div id="videoModal" class="modal" tabindex="-1" role="dialog">
        <div class="modal-dialog mt-5" role="document">
            <div class="modal-content">
                <div class="modal-header mx-auto">
                    <h5 class="modal-title">Add new video</h5>
                </div>
                <div class="modal-body">
                    <div class="mb-4 w-100">
                        <label asp-for="Input.VideoURL" class="form-label">ADD LINK</label>
                        <input asp-for="Input.VideoURL" class="form-control-plaintext" id="firstName" placeholder="Add new link">
                        <span asp-validation-for="Input.VideoURL" class="text-danger"></span>
                    </div>
                    <div class="mb-4 w-100">
                        <label asp-for="Input.VideoFile" class="form-label w-100">UPLOAD</label>
                        <input asp-for="Input.VideoFile" class="form-control" id="formFile" type="file" hidden accept="video/*" >
                        <label for="formFile" class="d-flex rounded-0 flex-row">
                            <span id="file-chosen" class="form-control-plaintext">Upload new video</span>
                            <div class="btn btn-primary">UPLOAD</div>
                        </label>
                    </div>  
                    <div class="modal-footer w-100">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                        <button type="submit" asp-page-handler="" class="btn btn-primary">Add</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
<script>
const fileChosen = document.getElementById('file-chosen');
const actualBtn = document.getElementById('formFile');
actualBtn?.addEventListener('change', function(){
    fileChosen.textContent = this.files[0].name
})
function sleep (time) {
    return new Promise((resolve) => setTimeout(resolve, time));
}
function showSearchBar() {
    document.getElementById("searchIcon").style.display = "none";
    document.getElementById("searchBar").style.display = "block";
    document.getElementById("search").focus();
}
function hideSearchBar(time) {
    sleep(time).then(() => { 
        document.getElementById("searchIcon").style.display = "block";
        document.getElementById("searchBar").style.display = "none";
    }
    )

}
</script>